server.port=8081
spring.datasource.url=jdbc:sqlite:/app/data/orders.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

temporal.target=temporal:7233
temporal.namespace=default
temporal.taskqueue=ORDER_TASK_QUEUE
